// Personalized from the reference's profile-specific video hero and content rows.
import {useState,useEffect} from 'react';
import {Link,useParams} from 'react-router-dom';
import {Play,Github,Linkedin,Menu,X,ArrowUpRight} from 'lucide-react';
import {profiles,profileViews,projects,skills,myInfo,artwork,Project} from '@/lib/data';
import ContentRow from '@/components/ContentRow';
import ProjectDialog from '@/components/ProjectDialog';
import Chatbot from '@/components/Chatbot';
import HeroVideo from '@/components/HeroVideo';
export default function ProfilePage(){const{profileType}=useParams();const profile=profiles.find(p=>p.type.toLowerCase()===profileType)||profiles[0];const view=profileViews[profile.type as keyof typeof profileViews];const[menu,setMenu]=useState(false),[selected,setSelected]=useState<Project|null>(null);const visible=(id:string)=>view.sections.includes(id);useEffect(()=>{window.scrollTo(0,0);setMenu(false)},[profile.type]);const items=projects.filter(p=>view.projects.includes(p.id));const jump=(event:React.MouseEvent<HTMLAnchorElement>,id:string)=>{event.preventDefault();document.getElementById(id)?.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});setMenu(false)};const nav=[['Home','home'],...view.sections.filter(id=>!['highlights','contact'].includes(id)).map(id=>[{experience:'Experience',projects:'Projects',skills:'Skills',about:'Education',credentials:'Credentials',journey:'Journey','research-focus':'Research'}[id],id]),['Contact','contact']];const metrics=profile.type==='Developer'?[['Explainable AI','DistilBERT · LIME · SHAP'],['Real-time systems','WebSockets · JWT · MERN'],['Multimodal AI','Text · audio · video · PDF']]:profile.type==='Adventurer'?[['Under 3 min','Adversarial runtime; previously 30–60 min'],['CPU ↔ NPU','AMD Ryzen AI hardware profiling'],['Interactive YOLOv2','Attack demo used by students']]:[['4 production agents','Slack, Teams and phone integrations'],['10–20 seconds','Error investigation; previously 10–15 min'],['3 environments','Dev, Staging and Production']];
return <div className="bg-netflix-black min-h-screen text-white"><header className="fixed top-0 inset-x-0 z-30 bg-black/50 backdrop-blur-md"><div className="flex items-center justify-between px-6 md:px-12 py-5"><Link to="/" className="font-bold text-2xl md:text-3xl tracking-tighter"><span className="text-netflix-red">TRINADH</span> <span className="hidden lg:inline">MUSUNURI</span></Link><nav className="hidden md:flex items-center gap-5 text-xs">{nav.map(([label,id])=><a key={id} href={'#'+id} onClick={e=>jump(e,id)} className="hover:text-netflix-red">{label}</a>)}<Link to="/profiles" aria-label="Change profile"><img src={'./lovable-uploads/'+profile.avatar} alt={profile.type} className="w-8 h-8 object-cover rounded"/></Link></nav><button className="md:hidden" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation" aria-expanded={menu}>{menu?<X/>:<Menu/>}</button></div>{menu&&<nav className="md:hidden p-6 bg-black flex flex-wrap gap-5 text-sm">{nav.map(([label,id])=><a key={id} href={'#'+id} onClick={e=>jump(e,id)}>{label}</a>)}<Link to="/profiles">Change profile</Link></nav>}</header>
<section id="home" className="relative min-h-[90dvh] flex items-center pt-28 pb-20"><HeroVideo key={profile.type} src={profile.video}/><div className="absolute inset-0 bg-gradient-to-r from-black/80 via-black/35 to-black/10"/><div className="absolute inset-0 bg-gradient-to-t from-netflix-black via-transparent to-black/30"/><div className="relative z-10 px-6 md:px-12 max-w-4xl animate-slide-in"><p className="text-xs tracking-[.25em] text-white/65 mb-6">TRINADH ORIGINAL · {profile.type.toUpperCase()} EDITION</p><h1 className="text-4xl md:text-6xl font-bold tracking-tight leading-tight" dangerouslySetInnerHTML={{__html:view.headline}}/><p className="text-sm md:text-lg text-white/80 mt-6 max-w-2xl leading-relaxed">{view.bio}</p><div className="flex flex-wrap gap-3 mt-8"><a href="./resume/Trinadh_Musunuri_Resume.pdf" target="_blank" rel="noopener noreferrer" className="cta-primary"><Play size={17} fill="currentColor"/>Resume</a><a href={myInfo.linkedin} target="_blank" rel="noopener noreferrer" className="cta-secondary"><Linkedin size={17}/>LinkedIn</a><a href={myInfo.github} target="_blank" rel="noopener noreferrer" className="cta-secondary"><Github size={17}/>GitHub</a></div></div></section>
<section className="px-6 md:px-12 py-8"><h2 className="section-title">Today's Top Picks for {profile.type.toLowerCase()}</h2><div className="grid grid-cols-2 md:grid-cols-5 gap-4 mt-6">{view.picks.map(([label,url],i)=><a key={label} href={url.startsWith('resume/')?'./'+url:url} onClick={e=>{if(url.startsWith('#'))jump(e,url.slice(1))}} target={url.startsWith('http')||url.endsWith('.pdf')?'_blank':undefined} rel="noopener noreferrer" className="aspect-video relative rounded-md overflow-hidden group card-hover"><img src={artwork[i%artwork.length]} alt="" className="h-full w-full object-cover"/><div className="absolute inset-0 bg-gradient-to-t from-black/95 via-black/30 to-transparent p-4 flex items-end justify-between"><span className="font-medium text-sm">{label}</span><ArrowUpRight size={16} className="opacity-0 group-hover:opacity-100"/></div></a>)}</div></section>
{visible('highlights')&&<section className="px-6 md:px-12 py-8"><h2 className="section-title">{profile.type==='Recruiter'?'Impact at a glance':profile.type==='Developer'?'Behind the builds':'Research with measurable results'}</h2><div className="grid md:grid-cols-3 gap-4 mt-6">{metrics.map(([value,label])=><article key={value} className="border-l-2 border-netflix-red bg-white/[.035] p-6"><strong className="text-2xl md:text-3xl">{value}</strong><p className="text-sm text-white/50 mt-3">{label}</p></article>)}</div></section>}
{visible('experience')&&<section id="experience" className="px-6 md:px-12 py-10"><h2 className="section-title">The experience behind the code</h2><div className="grid md:grid-cols-2 gap-5 mt-6"><article className="info-card"><p className="kicker">MAY–AUGUST 2026 · AUSTIN, TX</p><h3>IBM</h3><p className="text-white/80">Software Engineer Intern · watsonx Orchestrate</p><ul><li>Led Grafana observability dashboards for AI Gateway and Channel Integrations using Prometheus and Loki, reducing error investigation from 10–15 minutes to 10–20 seconds.</li><li>Deployed across Dev, Staging and Production in the SRE-managed repository.</li><li>Built a local voice runtime and CDR pipeline; resolved traffic bypassing AI Gateway with structured STT/TTS logs across three speech providers.</li><li>Built four omnichannel AI agents with React and a custom MCP server on AWS.</li></ul></article><article className="info-card"><p className="kicker">SEPTEMBER 2025–MAY 2026 · CMU</p><h3>Research Assistant</h3><ul><li>Replaced evolutionary optimization with a gradient-based approach, bringing adversarial ML experiments from 30–60 minutes to under three minutes.</li><li>Profiled AMD Ryzen AI NPU execution using cycle counting and DRAM contention metrics.</li><li>Designed CPU–NPU benchmarks contributing to hardware security research.</li><li>Built a student-facing YOLOv2 attack demo on Hugging Face Spaces with a Cloudflare Worker proxy.</li></ul></article></div></section>}
{visible('journey')&&<section id="journey" className="px-6 md:px-12 py-10"><h2 className="section-title">My journey so far</h2><div className="grid md:grid-cols-3 gap-5 mt-6">{[['2025–2026','Research at CMU','Adversarial machine learning and AMD Ryzen AI hardware performance.'],['SUMMER 2026','Building at IBM','Observability, voice infrastructure, and production AI agents.'],['MAY 2027','The next chapter','M.S. Computer Science and software engineering opportunities.']].map(([date,title,text])=><article key={title} className="info-card"><p className="kicker">{date}</p><h3>{title}</h3><p className="text-white/60 text-sm">{text}</p></article>)}</div></section>}
{visible('research-focus')&&<section id="research-focus" className="px-6 md:px-12 py-10"><h2 className="section-title">Research questions worth exploring</h2><div className="grid md:grid-cols-2 gap-5 mt-6">{projects.filter(p=>['yolo','npu'].includes(p.id)).map(p=><article key={p.id} className="info-card"><p className="kicker">{p.label}</p><h3>{p.title}</h3><ul>{p.details.map(t=><li key={t}>{t}</li>)}</ul></article>)}</div></section>}
{visible('projects')&&<ContentRow title={view.title} items={items} onSelect={setSelected}/>}
{visible('skills')&&<section id="skills" className="px-6 md:px-12 py-10"><h2 className="section-title">My engineering toolkit</h2><div className="grid md:grid-cols-3 gap-5 mt-6">{Object.entries(skills).map(([title,list])=><article key={title} className="info-card"><h3 className="!text-lg">{title}</h3><div className="flex flex-wrap gap-2 mt-4">{list.map(t=><span key={t} className="text-xs bg-white/5 border border-white/10 px-3 py-1.5 rounded">{t}</span>)}</div></article>)}</div></section>}
{visible('about')&&<section id="about" className="px-6 md:px-12 py-10"><div className="info-card"><p className="kicker">CLASS OF 2027</p><h2 className="text-3xl font-bold">Master of Science in Computer Science</h2><p className="mt-4 text-white/75">Central Michigan University · College of Science and Engineering</p><p className="text-white/50 text-sm mt-2">Mount Pleasant, Michigan · Expected graduation: May 2027</p><p className="text-sm text-white/60 mt-5">Advanced Algorithms · Cloud Computing · Web Technologies · Machine Learning</p></div></section>}
{visible('credentials')&&<section id="credentials" className="px-6 md:px-12 py-10"><h2 className="section-title">Learning and credentials</h2><div className="grid md:grid-cols-3 gap-5 mt-6">{[['NVIDIA · NOV 2025','Fundamentals of Deep Learning','https://learn.nvidia.com/certificates?id=h_6y4MSeQ_KLXWGKnuJkPA'],['GOOGLE CLOUD · NOV 2024','Generative AI Engineering','https://www.skills.google/public_profiles/7537c6b2-75aa-4f6d-9c96-be8f78859f0f'],['AWS · NOV 2023','Cloud Technical Essentials','https://www.coursera.org/account/accomplishments/certificate/GGN5MXGHUQEM']].map(([date,title,url])=><a key={title} href={url} target="_blank" rel="noopener noreferrer" className="info-card hover:border-white/30"><p className="kicker">{date}</p><h3 className="!text-xl">{title}</h3><p className="text-xs text-white/50 mt-4">View credential ↗</p></a>)}</div></section>}
<section id="contact" className="px-6 md:px-12 py-16"><p className="kicker">LET'S BUILD SOMETHING</p><h2 className="text-4xl md:text-5xl font-bold mt-3">Have a role in mind?</h2><p className="text-white/60 max-w-xl mt-5">I'm exploring software engineering opportunities in AI, cloud, systems, and full-stack development.</p><a className="cta-primary mt-7 inline-flex" href={'mailto:'+myInfo.email}>Email me <ArrowUpRight size={16}/></a></section><footer className="px-6 md:px-12 py-8 border-t border-white/10 flex flex-wrap justify-between gap-4 text-xs text-white/40"><span>© {new Date().getFullYear()} Trinadh Musunuri</span><Link to="/profiles">Switch profile</Link><a href="./resume/Trinadh_Musunuri_Resume.pdf" download>Download resume</a></footer><Chatbot/><ProjectDialog project={selected} onClose={()=>setSelected(null)}/></div>}
