import {useState,useRef,useEffect} from 'react';
import {MessageCircle,Send,X} from 'lucide-react';
import {loadHistory,saveHistory,limitHistory,type ChatTurn} from '../lib/chatHistory';
const greeting = {kind:'bot',text:"Hi! Ask me about Trinadh's experience, projects, or skills."};
export default function Chatbot(){const[open,setOpen]=useState(false),[input,setInput]=useState(''),[pending,setPending]=useState(false),[messages,setMessages]=useState(()=>[greeting,...loadHistory().map(m=>({kind:m.role==='user'?'user':'bot',text:m.content}))]);
 const history=useRef<ChatTurn[]>(loadHistory());
 const activeRequest=useRef<AbortController|null>(null);
 useEffect(()=>()=>{activeRequest.current?.abort()},[]);
 const newChat=()=>{if(busy.current)return;history.current=[];saveHistory([]);setMessages([greeting]);setInput('');field.current?.focus()};const field=useRef<HTMLInputElement>(null),log=useRef<HTMLDivElement>(null),busy=useRef(false);useEffect(()=>{if(open)field.current?.focus()},[open]);useEffect(()=>{if(log.current)log.current.scrollTop=log.current.scrollHeight},[messages,pending]);const send=async(text=input)=>{if(!text.trim()||busy.current)return;busy.current=true;setPending(true);setInput('');setMessages(m=>[...m,{kind:'user',text:text.trim()}]);const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),90000);activeRequest.current=controller;try{const res=await fetch('https://portfolio-chatbot-ozkz.onrender.com/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({input:text.trim(),history:history.current}),signal:controller.signal});if(!res.ok)throw Error();const data=await res.json();if(typeof data.message!=='string'||!data.message.trim()||data.message==='error')throw Error();
   if(controller.signal.aborted)return;
   history.current=limitHistory([...history.current,{role:'user',content:text.trim()},{role:'assistant',content:data.message}]);saveHistory(history.current);setMessages(m=>[...m,{kind:'bot',text:data.message}])}catch{setMessages(m=>[...m,{kind:'bot',text:'The assistant could not reply right now. Please try again.'}])}finally{clearTimeout(timer);activeRequest.current=null;busy.current=false;setPending(false);field.current?.focus()}};return <><button className="chat-launcher" aria-expanded={open} aria-controls="chat-panel" onClick={()=>setOpen(!open)}><MessageCircle size={18}/>Ask Trinadh's AI</button>{open&&<section id="chat-panel" className="chat-panel" role="dialog" aria-label="Trinadh's assistant" onKeyDown={e=>{if(e.key==='Escape')setOpen(false)}}><div className="flex justify-between items-center p-5 border-b border-white/10"><div><strong>Trinadh's Assistant</strong><p className="text-xs text-white/50 mt-1">Explore the story behind the code</p></div><div className="flex items-center gap-3"><button type="button" disabled={pending} onClick={newChat} className="text-xs text-white/70 disabled:opacity-40">New chat</button><button onClick={()=>setOpen(false)} aria-label="Close assistant"><X size={20}/></button></div></div><div ref={log} role="log" aria-live="polite" className="flex-1 overflow-y-auto p-5 flex flex-col gap-4">{messages.map((m,i)=><div key={i} className={'chat-message '+m.kind}>{m.text}</div>)}{pending&&<p role="status" className="text-sm text-white/50 animate-pulse">Thinking…</p>}</div><div className="flex gap-2 px-4 pb-3">{['IBM experience','Projects','Skills'].map(q=><button key={q} disabled={pending} onClick={()=>send('Tell me about Trinadh’s '+q)} className="text-[10px] px-3 py-1 border border-white/20 rounded-full">{q}</button>)}</div><form className="p-4 border-t border-white/10 flex gap-2" onSubmit={e=>{e.preventDefault();send()}}><input ref={field} aria-label="Message assistant" value={input} onChange={e=>setInput(e.target.value)} maxLength={2000} placeholder="Ask about my work…" className="min-w-0 flex-1 bg-white/10 rounded p-3 text-sm"/><button disabled={pending} className="bg-netflix-red p-3 rounded disabled:opacity-40" aria-label="Send message"><Send size={18}/></button></form></section>}</>}
